apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{ include "mychart.labels" . | indent  4}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      container:
      - name: {{ .Values.appName }}
        image: {{ .Values.image }}