{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.port }}
{{- end}}
