apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob 
spec:
  schedule: "*/1 * * * *" # every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: random-error
            image: bollapooja/random-exit
        restartPolicy: Never
