apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "3"
    deployment.kubernetes.io/max-replicas: "3"
    deployment.kubernetes.io/revision: "8"
    deployment.kubernetes.io/revision-history: "6"
    kubernetes.io/change-cause: updated image to tomcat
  creationTimestamp: "2025-04-23T07:34:28Z"
  generation: 4
  labels:
    app: nginx
    pod-template-hash: 84f6784f7c
  name: nginx-84f6784f7c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: nginx
    uid: b37d4d4e-6e17-4675-9899-2bdf68e6ebc5
  resourceVersion: "27430"
  uid: c6be459a-561e-498d-be2d-d9360aefe8e2
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
      pod-template-hash: 84f6784f7c
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-04-23T12:57:43+05:30"
      creationTimestamp: null
      labels:
        app: nginx
        pod-template-hash: 84f6784f7c
    spec:
      containers:
      - image: tomcat
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  observedGeneration: 4
  replicas: 0
