apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend1
  labels:
    app: nginx
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx 
